[package]
name = "flexllama-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
axum = "0.8.4"
ratatui = "0.29.0"
ratzilla = "0.1.0"
serde_json = "1.0.143"
tokio = {version="1.47.1", features=["full"]}
tracing = "0.1.41"
tracing-subscriber = "0.3.20"
